[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nesenv"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "numpy",
  "opencv-python",
  "stable-baselines3"
]

[tool.hatch.build.targets.wheel]
packages = ["nesenv"]